version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/mongodb/data/db
    networks:
      - mongo-network

volumes:
  mongo-data:
    driver: local

networks:
  mongo-network:
    driver: bridge
